unigraph_unit(Threading
  HEADERS
    scoped_thread.hpp
    thread.hpp
    thread_name.hpp
  SOURCES
    thread_name.cpp
    :windows
      windows/win32_thread_name.cpp
    :darwin:linux
      unix/pthread_thread_name.cpp
)
